=== Composition: *Eksport til protonregisteret*


undefined


===  *Utdanningssammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Høyeste fullførte utdanningsnivå** + 
 Type: `Coded text`  | Beskrivelse av det høyeste fullførte nivået av utdanning eller opplæring. 




*comment*: Koding av "Høyeste fullførte utdanningsnivå" med en terminologi er anbefalt der det er mulig. For eksempel med NUS 2000 eller Unescos ISCED klassifikasjon. Sistnevnte forefinnes ikke på norsk, men eksempel er "'Upper secondary vocational education"; "Post-secondary non-tertiary vocational education"; "Bachelor’s or equivalent level, professional"; "Doctoral or equivalent level, academic"; "Post-secondary non-tertiary vocational education"; or "Never attended an educational program".
a|

* Ingen utdanning +
 `no.utdanningsnivaa:0`
* Grunnskole +
 `no.utdanningsnivaa:1`
* Videregående +
 `no.utdanningsnivaa:2`
* Universitet/Høyskole <4 år +
 `no.utdanningsnivaa:3`
* Universitet/Høyskole ≥4 år +
 `no.utdanningsnivaa:4`
* Ukjent +
 `no.utdanningsnivaa:9`
| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da dette sammendraget om utdanning sist ble oppdatert. 




*comment*: Ved implementering av arketypen forutsettes det at dersom en utdanning eller opplæring legges til eller oppdateres i CLUSTER.education_record (Utdanning), vil også denne datoen oppdateres.
|
|====
===  *Arbeidssammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Arbeidsstatus** + 
 Type: `Coded text`  | Utsagn om individets nåværende jobb/rolle. 
a|

* I arbeid +
 `no.arbeidsstatus:1`
* Ikke i arbeid +
 `no.arbeidsstatus:2`
* Alderspensjonist +
 `no.arbeidsstatus:3`
* Under utdanning/studerer +
 `no.arbeidsstatus:4`
* Ukjent +
 `no.arbeidsstatus:9`
3+a|===== Arbeidsforhold/rolle  
| **Tittel/rolle** + 
 Type: `Text`  | Stillingstittel eller betegnelse for dette arbeidsforholdet/rollen/vervet. 
a|

3+a|===== Sykemelding  
| **Sykemelding - fra dato** + 
 Type: `Date/time`  | Startdatoen for sykemeldingen. 




*comment*: Startdatoen for sykemeldingen.
|
| **Varighet** + 
 Type: `Duration`  | Varigheten av sykemeldinsperioden til individet. 




*comment*: Varigheten av sykemeldinsperioden til individet.
|
| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da arbeidssammendraget eller tilknyttede arbeidsepisoder sist ble oppdatert. 




*comment*: Ved implementering av arketypen forutsettes det at dersom en arbeidsepisode legges til eller oppdateres, vil også denne datoen oppdateres.
|
|====
===  *Sosialt nettverk*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Samlivsstatus** + 
 Type: `Coded text`  | Enkeltord eller frase som beskriver et individs nåværende forhold til en livspartner. 




*comment*: Verdisettet for dataelementet "Samlivsstatus" er standardisert med bakgrunn i variabler fra SSB (https://www.ssb.no/klass/klassifikasjoner/19).

a|

* Ugift/enslig +
 `no.samlivsstatus:1`
* Gift/samboer/registrert partner +
 `no.samlivsstatus:2`
* Enke/enkemann/gjenlevende partner eller samboer +
 `no.samlivsstatus:3`
* Skilt/separert +
 `no.samlivsstatus:4`
* Ukjent +
 `no.samlivsstatus:9`
| **Kommentar** + 
 Type: `Text`  | Ytterligere fritekst om det sosiale nettverket som ikke er registrert i andre felt. 
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da det sosiale nettverket siste ble oppdatert. 




*comment*: Datoen da samlivsstatus sist ble oppdatert.
|
|====
===  *Kartleggingspørsmål om sosiale forhold samlivsform*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Kartleggingsformål** + 
 Type: `Coded text`  | Konteksten eller årsaken for kartleggingen. 




*comment*: Dette dataelementet er ment for å sette en kontekst for samlingen av spørsmål/svar til bruk senere for å gjøre spørringer på dataene. Det er ikke forventet at dette dataelementet skal være synlig for en bruker av skjemaet, men kun tilgjengelig i de lagrede dataene. For eksempel: "Preoperativ screening" eller navnet på det faktiske spørreskjemaet.
a|

* Samlivsform +
 `no.onk.sosiale_forhold:SAM`
3+a|===== Spesifikt sosialt forhold  
| **Hvilken samlivsform har pasienten?** + 
 Type: `Coded text` (_mandatory_) | Navngiving av et spesifikt sosialt forhold, problem eller bekymring som er relevant for spørreskjemaet, eller en gruppering av slike. 




*comment*: Dette elementet tilbyr valg mellom fritekst og kodet tekst. Det er antatt at listen av kodede verdier vil vokse ettersom man identifiserer flere behov. Det er anbefalt å kode "Sosialt forhold" med en terminologi dersom det er mulig - for eksempel relevante termer innen hierarkiet til SNOMED CT's Social context finding hierarchy (SCTID: 108329005). Alternativt som fritekst, for eksempel "Forsørgelsesbyrde", "Sosial isolasjon", "Diskriminering", "Minoritetsstress".
a|

* Bor alene (Inkl. alene med barn <18) +
 `no.samlivsform:1`
* Bor med noen (Partner og/eller med barn >18 år, bofelleskap, venner) +
 `no.samlivsform:2`
* Bor på institusjon/ sykehjem (Fast plass, ikke korttidsopphold. Gjelder også der egen bolig er døgnbemannet) +
 `no.samlivsform:3`
* Ukjent +
 `no.samlivsform:9`
|====
===  *Kartlegging omsorgsansvar*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Kartleggingsformål** + 
 Type: `Coded text`  | Konteksten eller årsaken for kartleggingen. 




*comment*: I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for kartleggingsformål. no.onk.sosiale_forhold.
a|

* Kartlegging av om individet har omsorgsansvar +
 `no.onk.sosiale_forhold:OA`
3+a|===== Omsorgsperson for barn under 18 år  
| **Sosialt forhold** + 
 Type: `Coded text` (_mandatory_) | Navngiving av et spesifikt sosialt forhold, problem eller bekymring som er relevant for spørreskjemaet, eller en gruppering av slike. 




*comment*: Navngiving av et spesifikt sosialt forhold.
a|

* Ansvarlig for barn under 18 år +
 `no.onk.sosiale_forhold:U18`
| **Har pasienten ansvar for barn under 18 år?** + 
 Type: `Coded text`  | Har individet hatt noen erfaring med det spesifiserte "Sosialt forhold"? 
a|

* Ja
* Nei
* Ukjent
3+a|===== Barn som pårørende  
| **Sosialt forhold** + 
 Type: `Coded text` (_mandatory_) | Navngiving av et spesifikt sosialt forhold, problem eller bekymring som er relevant for spørreskjemaet, eller en gruppering av slike. 




*comment*: Navngiving av et spesifikt sosialt forhold.
a|

* Barn som pårørende +
 `no.onk.sosiale_forhold:BPU18`
| **Finnes det barn som pårørende?** + 
 Type: `Coded text`  | Har individet hatt noen erfaring med det spesifiserte "Sosialt forhold"? 
a|

* Ja
* Nei
* Ukjent
| **Kommentar** + 
 Type: `Text`  | Ytterligere fritekst om det spesifikke sosiale forholdet som ikke er omfattet av andre felt. 
a|

3+a|===== Omsorgsperson for personer over 18 år  
| **Sosialt forhold** + 
 Type: `Coded text` (_mandatory_) | Navngiving av et spesifikt sosialt forhold, problem eller bekymring som er relevant for spørreskjemaet, eller en gruppering av slike. 




*comment*: Navngiving av et spesifikt sosialt forhold.
a|

* Ansvarlig for barn/andre over 18 år +
 `no.onk.sosiale_forhold:O18`
| **Har pasienten ansvar for egne barn/andre over 18 år?** + 
 Type: `Coded text`  | Har individet hatt noen erfaring med det spesifiserte "Sosialt forhold"? 
a|

* Ja
* Nei
* Ukjent
|====
===  *Fritekst relatert til sosial anamnese*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Fritekst relatert til sosial anamnese** + 
 Type: `Text`  | Fritekstbeskrivelse av helserelaterte hendelser, status, funn eller oppfatninger på et spesifikt tidspunkt. 
a|

3+a|===== Semistrukturert metadata dips  **[multiple]**
| **Klassifisering av informasjon** + 
 Type: `Coded text`  | * 
a|

* Sosial anamnese +
 `no.dips.Freetext.Classification:01-Oncology-Sosial-anamnese`
|====
===  *Alkohol*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Overordnet status** + 
 Type: `Coded text`  | Utsagn om nåværende atferd og bruk for alle typer alkohol. 
a|

* Nåværende bruker
* Tidligere bruker
* Aldri brukt
| **Overordnet beskrivelse** + 
 Type: `Text`  | Oppsummering i fritekst om et individs overordnede mønster og historie knyttet til alkoholinntak. 




*comment*: Bruk dette elementet for å registrere en beskrivelse i fritekst om drikkevaner for dette individet.
a|

3+a|===== Per episode  
| **Typisk bruk (alkoholenheter)** + 
 Type: `Quantity`  | Estimat på antall alkoholenheter som ble drukket. 
a|

Valid units: +

* 1/wk
* 1/d
* 1/mo
| **Sist oppdatert** + 
 Type: `Date/time`  | Dato når sammendraget av alkoholbruk sist ble oppdatert. 
|
|====
===  *Røyk*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Overordnet status** + 
 Type: `Coded text`  | Utsagn om nåværende røykeadferd for alle typer tobakk. 
a|

* Aldri røykt
* Røyker
* Tidligere røyker
| **Overordnet beskrivelse** + 
 Type: `Text`  | Fritekstsammendrag om individets overordnede røykemønster og historikk. 




*comment*: Bruk dette datalementet til å registrere en fritekstbeskrivelse av individets tobakksrøykevaner.
a|

| **Samlet pakkeår** + 
 Type: `Count`  | Anslått kumulativ mengde av alle tobakkstyper som er røykt. 




*comment*: Anslått kumulativ mengde av alle tobakkstyper som er røykt.
a|

Range: +

* >= 0 and undefined undefined
| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da sammendraget av tobakksbruk sist ble oppdatert. 
|
|====
===  *Røykfri tobakk/snus*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Overordnet status** + 
 Type: `Coded text`  | Utsagn om nåværende bruksmønster for alle typer røykfri tobakk. 
a|

* Aldri brukt
* Nåværende bruker
* Tidligere bruker
| **Overordnet beskrivelse** + 
 Type: `Text`  | Fritekstsammendrag om individets overordnede bruksmønster og historikk for røykfri tobakk. 




*comment*: Bruk dette datalementet til å registrere en fritekstbeskrivelse av individets bruk av røykrfri tobakk.
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da sammendraget av bruk av røykfri tobakk sist ble oppdatert. 
|
|====
===  *Sammendrag andre substanser*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Substansnavn** + 
 Type: `Coded text` (_mandatory_) | Navnet på substansen eller klassen av substanser. 




*comment*: Koding med ekstern terminologi anbefales om det er mulig.
a|

* Annen substans +
 `no.onk.substansbruk:osub`
| **Overordnet beskrivelse** + 
 Type: `Text`  | Fritekstsammendrag om bruk av substansen gjennom individets livsløp. 




*comment*: Bruk dette datalementet til å registrere en fritekstbeskrivelse av individets bruk av andre substanser.
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da Substansbruk sist ble oppdatert. 
|
|====
===  *Substansanamnese*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Substansnavn** + 
 Type: `Text` (_mandatory_) | Navnet på substansen eller klassen av substanser. 




*comment*: Koding med ekstern terminologi anbefales om det er mulig.
a|

| **Overordnet status** + 
 Type: `Coded text`  | Utsagn om nåværende substansbruk, uavhengig av administrasjonsvei. 
a|

* Aldri brukt
* Nåværende bruker
* Tidligere bruker
| **Overordnet beskrivelse** + 
 Type: `Text`  | Fritekstsammendrag om bruk av substansen gjennom individets livsløp. 




*comment*: Bruk dette datalementet til å registrere en fritekstbeskrivelse av individets bruk av andre substanser.
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da Substansbruk sist ble oppdatert. 
|
|====
===  *Kartlegging komorbiditet*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Kartleggingsformål** + 
 Type: `Coded text`  | Konteksten eller årsaken for kartleggingen. 




*comment*: I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for kartleggingsformål. no.onk.screening.problem.
a|

* Komorbiditet +
 `no.onk.screening.problem:kom`
| **Har pasient kjent komorbiditet?** + 
 Type: `Coded text`  | Finnes det noen bekymringer, plager, problemer eller diagnoser. som er innenfor kartleggingsformålet? 
a|

* Ja
* Nei
* Ukjent
| **Overordnet merknad komorbiditet** + 
 Type: `Text`  | Fritekstbeskrivelse om bekymringer, plager, problemer eller diagnoser som er innenfor kartleggingsformålet. 
a|

|====
===  *Forholdsregel*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Tilstand: Hovedkapitler ICD-10** + 
 Type: `Coded text` (_mandatory_) | Navnet på tilstanden eller statusen. 




*comment*: I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for hovedkapitler i ICD-10, no.icd10.kapitler.
a|

* Infeksjonssykdommer og parasittsykdommer, visse sykd. (Kap.I; A00-B99) +
 `no.icd10.kapitler:I`
* Svulster (Kap.II; C00-D48) +
 `no.icd10.kapitler:II`
* Blodsykdommer og sykdom i bloddannende organer og visse tilstander som angår immunsystemet (Kap.III; D50-D89) +
 `no.icd10.kapitler:III`
* Endokrine sykdommer, ernæringssykdommer og metabolske forstyrrelser (Kap.IV; E00-E90) +
 `no.icd10.kapitler:IV`
* Psykiske lidelser og atferdsforstyrrelser (Kap.V; F00-F99) +
 `no.icd10.kapitler:V`
* Nervesystemet, sykdommer (Kap.VI; G00-G99) +
 `no.icd10.kapitler:VI`
* Øyet og øyets omgivelser, sykdommer (Kap.VII; H00-H59) +
 `no.icd10.kapitler:VII`
* Øre og ørebensknute (processus mastoideus), sykdommer (Kap.VIII; H60-H95) +
 `no.icd10.kapitler:VIII`
* Sirkulasjonssystemet, sykdommer (Kap.IX; I00-I99) +
 `no.icd10.kapitler:IX`
* Åndedrettssystemet, sykdommer (Kap.X; J00-J99) +
 `no.icd10.kapitler:X`
* Fordøyelsessystemet, sykdommer (Kap.XI; K00-K93) +
 `no.icd10.kapitler:XI`
* Hud og underhud, sykdommer (Kap.XII; L00-L99) +
 `no.icd10.kapitler:XII`
* Muskel-skjelettsystemet og bindevev, sykdommer (Kap.XIII; M00-M99) +
 `no.icd10.kapitler:XIII`
* Urin- og kjønnsorganer, sykdommer (Kap.XIV; N00-N99) +
 `no.icd10.kapitler:XIV`
* Svangerskap, fødsel og barseltid (Kap.XV; O00-O99) +
 `no.icd10.kapitler:XV`
* Perinatalperioden  - visse tilstander som oppstår (Kap.XVI; P00-P96) +
 `no.icd10.kapitler:XVI`
* Medfødte misdannelser, deformiteter og kromosomavvik (Kap.XVII; Q00-Q99) +
 `no.icd10.kapitler:XVII`
* Symptomer, tegn, unormale kliniske funn og laboratoriefunn, ikke klassifisert annet sted (Kap.XVIII; R00-R99) +
 `no.icd10.kapitler:XVIII`
* Skader, forgiftninger og visse andre konsekvenser av ytre årsaker (Kap.XIX; S00-T98) +
 `no.icd10.kapitler:XIX`
| **Detaljer** + 
 Type: `Text`  | Beskrivelse av underlaget som understøtter forholdsregelen. 
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Dato da forholdsregelinformasjonen sist ble oppdatert. 
|
|====
===  *Forholdsregel*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Tilstand: ICD-10** + 
 Type: `Text` (_mandatory_) | Navnet på tilstanden eller statusen. 




*comment*: I strukturert kreftjournal er dette elementet koblet til et ICD-10 søk.
a|

| **Detaljer** + 
 Type: `Text`  | Beskrivelse av underlaget som understøtter forholdsregelen. 
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Dato da forholdsregelinformasjonen sist ble oppdatert. 
|
|====
===  *Charlson Comorbidity Index (CCI)*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Aldersgruppe** + 
 Type: `Ordinal`  | Alderskategorien til pasienten. 
a|
* [0] <50 år +
 `local:at0062`
* [1] 50-59 år +
 `local:at0063`
* [2] 60-69 år +
 `local:at0064`
* [3] 70-79 år +
 `local:at0065`
* [4] ≥80 år +
 `local:at0066`
| **Myokardinfarkt** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0013`
* [1] Ja +
 `local:at0014`
| **Kronisk hjertesvikt** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0010`
* [1] Ja +
 `local:at0011`
| **Perifere vaskulære sykdommer** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0007`
* [1] Ja +
 `local:at0008`
| **Cerebrovaskulær hendelse** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0016`
* [1] Ja +
 `local:at0017`
| **Demens** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0019`
* [1] Ja +
 `local:at0020`
| **Kronisk lungesykdom** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0022`
* [1] Ja +
 `local:at0023`
| **Ulcussykdom** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0025`
* [1] Ja +
 `local:at0026`
| **Leversykdom** + 
 Type: `Ordinal`  |  
a|
* [0] Ingen +
 `local:at0028`
* [1] Mild +
 `local:at0029`
* [3] Moderat til alvorlig +
 `local:at0067`
| **Bindevevssykdom** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0031`
* [1] Ja +
 `local:at0032`
| **Diabetes** + 
 Type: `Ordinal`  |  
a|
* [0] Ingen eller diettkontrollert +
 `local:at0034`
* [1] Ukomplisert +
 `local:at0035`
* [2] Organskade +
 `local:at0068`
| **Hemiplegi** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0037`
* [2] Ja +
 `local:at0038`
| **Moderat til alvorlig nyresykdom** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0040`
* [2] Ja +
 `local:at0041`
| **Solid svulst** + 
 Type: `Ordinal`  |  
a|
* [0] Ingen +
 `local:at0046`
* [2] Lokalisert +
 `local:at0048`
* [6] Metastatisk +
 `local:at0069`
| **Leukemi** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0049`
* [2] Ja +
 `local:at0051`
| **Lymfom** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0052`
* [2] Ja +
 `local:at0053`
| **AIDS** + 
 Type: `Ordinal`  |  
a|
* [0] Nei +
 `local:at0070`
* [6] Ja +
 `local:at0071`
| **CCI totalskår** + 
 Type: `Count`  | Summen av poeng for hver enkelt parameter i Charlson Comorbidity Index. 
a|

|====
===  *Høyde/Lengde*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Høyde/lengde** + 
 Type: `Quantity` (_mandatory_) | Høyde/lengde fra isse til fotsåle. 
a|

Valid units: +

* cm
|====
===  *Kroppsvekt*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Kroppsvekt** + 
 Type: `Quantity` (_mandatory_) | Et individs totale kroppsmasse. 
a|

Valid units: +

* kg
|====
===  *Kroppsmasseindeks*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Kroppsmasseindeks** + 
 Type: `Quantity` (_mandatory_) | Indeks som beskriver forholdet mellom vekt og høyde. 
a|

Valid units: +

* kg/m2
|====
===  *ECOG funksjonsstatus*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **ECOG funksjonsstatus** + 
 Type: `Ordinal` (_mandatory_) | Funksjonsstatus hos en pasient med kreft. 
a|
* [0] Asymptomatisk +
 `local:at0005`
* [1] Symptomatisk, fullt oppegående +
 `local:at0006`
* [2] Symptomatisk, sengeliggende <50 % av våken tid +
 `local:at0007`
* [3] Symptomatisk, sengeliggende > 50 % av våken tid +
 `local:at0008`
* [4] Helt sengeliggende +
 `local:at0009`
* [5] Død +
 `local:at0010`
|====
===  *Karnofsky Performance Status (KPS) scale*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Karnofsky performance status** + 
 Type: `Ordinal` (_mandatory_) |  
a|
* [100] Normal, ingen plager eller subjektive tegn på sykdom. +
 `local:at0015`
* [90] Klarer normal aktivitet, sykdommen gir lite symptomer. +
 `local:at0014`
* [80] Klarer med nød normal aktivitet. Sykdommen gir en del symptomer. +
 `local:at0013`
* [70] Klarer seg selv, ute av stand til normal aktivitet eller aktivt arbeid. +
 `local:at0012`
* [60] Trenger noe hjelp, men klarer stort sett å tilfredsstille egne behov. +
 `local:at0011`
* [50] Trenger betydelig hjelp og stadig medisinsk omsorg. +
 `local:at0010`
* [40] Ufør, trenger spesiell hjelp og omsorg. +
 `local:at0009`
* [30] Helt ufør, hospitalisering nødvendig, men fare for død er ikke overhengende. +
 `local:at0008`
* [20] Svært syk, hospitalisering og understøttende behandling nødvendig. +
 `local:at0007`
* [10] Moribund, dødsprosessen er i sterk frammarsj. +
 `local:at0006`
* [0] Død. +
 `local:at0005`
|====
===  *Kartlegging om tidligere kreftbehandling*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Kartleggingsformål** + 
 Type: `Coded text`  | Konteksten eller årsaken for kartleggingen. 




*comment*: I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for kartleggingsformålet no.onk.kart.tidligere_kreftbehandling.
a|

* Sarkom +
 `no.onk.kart.tidligere_kreftbehandling:1`
* Kreft i hode og hals +
 `no.onk.kart.tidligere_kreftbehandling:2`
* Hjernesvulst +
 `no.onk.kart.tidligere_kreftbehandling:3`
* Brystkreft +
 `no.onk.kart.tidligere_kreftbehandling:4`
* Lungekreft +
 `no.onk.kart.tidligere_kreftbehandling:5`
* Kreft i fordøyelsessystemet +
 `no.onk.kart.tidligere_kreftbehandling:6`
* Gynekologisk kreft +
 `no.onk.kart.tidligere_kreftbehandling:7`
* Kreft i nyre og urinveier +
 `no.onk.kart.tidligere_kreftbehandling:8`
* Benmargs- og blodkreft +
 `no.onk.kart.tidligere_kreftbehandling:9`
* Lymfom +
 `no.onk.kart.tidligere_kreftbehandling:10`
* Hudkreft +
 `no.onk.kart.tidligere_kreftbehandling:11`
* Kreft i mannlige kjønnsorganer +
 `no.onk.kart.tidligere_kreftbehandling:12`
* Kreft i endokrine kjertler +
 `no.onk.kart.tidligere_kreftbehandling:13`
* Nevroendokrin kreft +
 `no.onk.kart.tidligere_kreftbehandling:14`
* Barnekreft +
 `no.onk.kart.tidligere_kreftbehandling:15`
* Øyekreft +
 `no.onk.kart.tidligere_kreftbehandling:16`
* Svulst av ukjent opprinnelse / Annet +
 `no.onk.kart.tidligere_kreftbehandling:17`
| **Har pasienten hatt tidligere kreftbehandling?** + 
 Type: `Coded text` (_multiple_) | Finnes det noen tidligere gjennomførte prosedyrer som som er innenfor kartleggingsformålet? 
a|

* Ja
* Nei
* Ukjent
| **Beskrivelse** + 
 Type: `Text`  | Fritekstbeskrivelse om prosedyrer som er tidligere utført og som er innenfor kartleggingsformålet. 
a|

3+a|===== Spesifikk prosedyre  **[multiple]**
| **Prosedyrenavn** + 
 Type: `Coded text` (_mandatory_) | Navnet på en prosedyre eller gruppe av prosedyrer. 
a|

* Kirurgisk fjerning +
 `SNOMED-CT:128303001`
* Ablation +
 `SNOMED-CT:64597002`
* Stråleterapi (alle typer) +
 `SNOMED-CT:1287742003`
* Fotonterapi - Stråle (ekstern) +
 `SNOMED-CT:1156506007`
* Protonterapi -Stråle (ekstern) +
 `SNOMED-CT:169314007`
* Elektronterapi - Stråle (ekstern) +
 `SNOMED-CT:45643008`
* Brakyterapi - Stråle (intern) +
 `SNOMED-CT:152198000`
* Radioisotope/systemisk radionuklidebehandling - Stråle (intern) +
 `SNOMED-CT:399315003`
* Medikamentell behandling (alle typer) +
 `SNOMED-CT:416608005`
* Kjemoterapi - Medikamentell +
 `SNOMED-CT:367336001`
* Målrettet - Medikamentell +
 `SNOMED-CT:347531000202105`
* Immunterapi - Medikamentell behandling +
 `SNOMED-CT:76334006`
* Hormonterapi - Medikamentell +
 `SNOMED-CT:169413002`
* Annen behandling +
 `SNOMED-CT:74964007`
* Ingen kreftbehandling, aktiv oppfølging +
 `SNOMED-CT:373818007`
* Ekseptans +
 `SNOMED-CT:438758006`
| **Utført?** + 
 Type: `Coded text`  | Har den identifiserte prosedyren vært utført? 
a|

* Ja
* Nei
* Ukjent
| **Behandlingsstart** + 
 Type: `Date/time`  | Tidsangivelse for prosedyren. 
|
| **Behandlingsslutt** + 
 Type: `Date/time`  | Tidsangivelse for prosedyren. 
|
| **Kommentar** + 
 Type: `Text`  | Ytterligere fritekst om det spesifikke prosedyrespørsmålet som ikke er omfattet av andre felt. 
a|

|====
===  *Kartlegging av Sykdomsutvikling (tumor event)*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
3+a|===== Spesifikt problem eller diagnose  
| **Problem/diagnosenavn** + 
 Type: `Coded text` (_mandatory_) | Sykdomsutvikling (patologisk prosess) hos pasienten. 




*comment*: Koding av problem/diagnosenavnet med en terminologi foretrekkes, der det er mulig.
a|

* Tumorhendelse (patologisk prosess) +
 `SNOMED-CT:308489006`
| **Har det skjedd sykdomsutvikling (tumor event) siden sist kontakt?** + 
 Type: `Boolean`  | Har det skjedd en sykdomsutvikling (engelsk: tumor-event) i form av residiv eller progresjon siden siste kontroll. 




*comment*: Navnet på dataelementet kan omformuleres til det spesifikke spørsmålet i et templat eller brukergrensesnitt. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
|
| **Hendelsestidspunkt** + 
 Type: `Date/time`  | Tidsangivelsen for når sykdomsutviklingen (tumor event) ble oppdaget. 




*comment*: Dataelementet "Tidsangivelse" er med hensikt løst modellert for å støtte ulike måter å angi tidsangivelser for bekymringen, plagen, problemet eller diagnosen i et spørreskjema. Den konkrete semantikken defineres i templatet. For eksempel: Bekymringen, plagen, problemet eller diagnosen faktiske dato og/eller klokkeslett, start- og slutttid for bekymringen, plagen, problemet eller diagnosen, et tidsintervall for når bekymringen, plagen, problemet eller diagnosen oppstod, varigheten av bekymringen, plagen, problemet eller diagnosen, individets alder på tidspunktet for bekymringen, plagen, problemet eller diagnosen, eller hvor lenge det siden det oppstod. Kan være en deldato, for eksempel bare år, ved å bruke datatypen DV_DATE_TIME.
|
3+a|===== Tumor hendelse dips  
| **Dato for forrige sykdomsutvikling (tumor event)** + 
 Type: `Date/time`  | Dato for forrige sykdomsutvikling, hentet fra elementet "Hendelsestidspunkt" i det siste polikliniske notat hvor det er svart ja på spørsmålet om det er noen sykdomsutvikling. 
|
|====
===  *Problem/diagnose*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Problem/diagnosenavn (hentet fra ander dokumenter hvis de finnes)** + 
 Type: `Text` (_mandatory_) | Identifisering av problemet eller diagnosen ved hjelp av navn. 




*comment*: Koding av navnet på problemet eller diagnosen med en terminologi er foretrukket, der det er mulig.
a|

| **Variant** + 
 Type: `Text` (_multiple_) | Spesifikk variant eller subtype av diagnose, hvis det er relevant. 




*comment*: For eksempel "akutt motorisk aksonal nevropati" som en variant av Guillain-Barre Syndrom. Koding av navnet på varianten med en terminologi er foretrukket hvis mulig.
a|

3+a|===== Problem/diagnose-kvalifikator  
| **Residiv eller progresjon** + 
 Type: `Coded text`  | Hvilken sykdomsutvikling (engelsk: tumor-event) i form av residiv eller progresjon er tilstede? 




*comment*: For eksempel status for kreft eller en hematologisk diagnose.
a|

* Residiv (av tumor) +
 `SNOMED-CT:25173007`
* Progresjon +
 `SNOMED-CT:419835002`
3+a|===== Klinisk grunnlag  
| **Funn** + 
 Type: `Coded text`  | Den spesifiserte hendelsestypen for sykdomsutviklingen. 




*comment*: Det anbefales å kode "Funn" med en terminologi, der det er mulig.
a|

* Tumorhendelse (patologisk prosess) +
 `SNOMED-CT:308489006`
| **Resultat** + 
 Type: `Coded text` (_multiple_) | Måling eller verdi knyttet til funnet. 




*comment*: For eksempel mantouxtestresultat.
a|

* Lokalt +
 `no.onc.tumorevent.hendelse:01`
* Regionalt +
 `no.onc.tumorevent.hendelse:02`
* Metastasert +
 `no.onc.tumorevent.hendelse:03`
* Biokjemisk +
 `no.onc.tumorevent.hendelse:04`
| **Dato** + 
 Type: `Date/time`  | Datoen da funnet ble klinisk anerkjent. 




*comment*: For eksempel: Datoen da funnet ble gjort eller gjort tilgjengelig for klinikeren.
|
| **Metode** + 
 Type: `Coded text` (_multiple_) | Typen undersøkelse eller utredning som er utført for å komme fram til funnet. 




*comment*: Metoden bør vurderes kodet med en terminologi der dette er mulig. For eksempel fysisk undersøkelse, røntgen thorax, patologisvar, koloskopi.
a|

* Biokjemisk test +
 `SNOMED-CT:41289000`
* Klinisk (fysisk) undersøkelse +
 `SNOMED-CT:5880005`
* Bildediagnostikk +
 `SNOMED-CT:363679005`
* Histologisk test +
 `SNOMED-CT:714797009`
| **Beskrivelse av påvisningsmetode** + 
 Type: `Text`  | Fritekstlig beskrivelse av typen undersøkelse eller utredning som er utført for å komme fram til funnet. 
a|

| **Kommentar** + 
 Type: `Text`  | Ytterligere informasjon om funnet, som ikke kan registreres i andre felter. 
a|

| **Diagnostisk sikkerhet** + 
 Type: `Coded text`  | Grad av sikkerhet i identifikasjonen av diagnosen. 




*comment*: Hvis et alternativt verdisett er nødvendig, kan disse verdiene legges til DV_TEXT-datatypen i et templat.
a|

* Mistenkt
* Sannsynlig
* Bekreftet
| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da problemet eller diagnosen sist ble oppdatert. 
|
|====
===  *Problem/diagnose (inkl TNM)*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Problem/diagnosenavn** + 
 Type: `Coded text` (_mandatory_) | Identifisering av problemet eller diagnosen ved hjelp av navn. 




*comment*: Primærdiagnosen kodet som ICD-10
a|
| **Variant** + 
 Type: `Text` (_multiple_) | Spesifikk variant eller subtype av diagnose, hvis det er relevant. 




*comment*: For eksempel "akutt motorisk aksonal nevropati" som en variant av Guillain-Barre Syndrom. Koding av navnet på varianten med en terminologi er foretrukket hvis mulig.
a|

| **Klinisk beskrivelse** + 
 Type: `Text`  | Fritekstbeskrivelse av problemet eller diagnosen. 




*comment*: Brukes i Sarkom med endret navn til "Merknad" 

Brukes til å gi bakgrunn og kontekst, inkludert utvikling, episoder eller forverringer, fremgang og alle andre relevante detaljer, om problemet eller diagnosen.
a|

| **Anatomisk lokalisering** + 
 Type: `Coded text`  | Registrering av et enkelt og usammensatt anatomisk sted der problemet eller diagnosen er lokalisert. 




*comment*: Koding av navnet på den anatomiske lokaliseringen ved hjelp av en terminologi er foretrukket når dette er mulig. 
Bruk dette dataelementet for å registrere prekoordinerte anatomiske lokaliseringer. Dersom behovene for å registrere anatomisk sted bestemmes i applikasjonen eller trenger større grad av kompleksitet som f.eks. relativ lokalisering, er det anbefalt å bruke CLUSTER.anatomical_location eller CLUSTER.relative_location innenfor SLOTet "Strukturert anatomisk lokalisering" i denne arketypen. Dette dataelementet kan ha ubegrenset antall forekomster, for å gjøre det mulig å registrere kliniske scenarier som f.eks. å beskrive et utslett som opptrer flere steder på kroppen, men der alle andre attributter er identiske. Dersom den anatomiske lokaliseringen inkluderes i feltet "Problem/diagnosenavn" via prekoordinerte koder blir dette dataelementet overflødig.
a|

* Erstattes med kode fra script eller gjenbruk +
 `SNOMED-CT:x`
3+a|===== Anatomisk lokalisering  **[multiple]**
| **Navn på kroppssted** + 
 Type: `Text` (_mandatory_) | Navngiving av et enkelt fysisk sted enten på eller i menneskekroppen. 
a|

| **Spesifikt sted** + 
 Type: `Text` (_multiple_) | Ytterligere detaljer gitt ved hjelp av en spesifikk region eller et punkt på eller i det spesifiserte kroppsstedet. 




*comment*: Brukes tilå øke presisjonen ved spesifisering av kroppsstedet, dersom påkrevd. For eksempel den øvre høyre kvadranten eller McBurneys punkt på bukveggen, eller interfalangealleddet på stortåen. Dersom dataelementet "Navn på kroppssted" er registrert ved hjelp av prekoordinerte termer som omfatter det spesifikke stedet er dette dataelementet overflødig. I de fleste tilfeller vil dette være ett enkelt sted på kroppen. Dataelementet åpner for flere forekomster i de sjeldne tilfellene der man trenger å angi et spesifikt anatomisk sted som omfatter to eller flere sammenhengende spesifikke steder. For eksempel for å beskrive det spesifikke stedet en svulst strekker seg over andre, tredje og fjerde ribben.
a|

| **Kroppsside** + 
 Type: `Coded text`  | Den identifiserte kroppssiden. 




*comment*: Hvis den identifiserte kroppssiden ikke har noen lateralitet, bør dette datalementet stå tomt. Hvis dataelementet "Navn på kroppsted" bruker prekoordinerte termer som inkluderer lateralitet, er dette dataelementet overflødig.
a|

* Høyre +
 `SNOMED-CT:24028007`
* Venstre +
 `SNOMED-CT:7771000`
* Annet +
 `SNOMED-CT:74964007`
| **Beskrivelse** + 
 Type: `Text`  | Fritekstbeskrivelse som kan brukes for å ytterligere presisere og støtte "Navn på kroppsted". 




*comment*: B
a|

| **Årsak** + 
 Type: `Text`  | En årsak, kjede av årsaker til, eller hendelsesforløp forut for problemet eller diagnosen. 




*comment*: I Sarkom benyttes feltet kodet med mulig verdi: 

SNOMED-CT::1340012009|Stråleindusert|

Også kjent som 'etiologi'. Det anbefales å kode "Årsak" med en ekstern terminologi dersom det er mulig.
a|

| **Dato/tid for klinisk bekreftelse** + 
 Type: `Date/time`  | Anslått eller faktisk dato/tid da diagnosen ble bekreftet: prøvetakningsdato for første positiv histologi/cytologi (evt. mottaksdato så svardato for patologiprøve). Dersom det ikke er tatt vevsprøver, benyttes den dato man ved hjelp av andre undersøkelser (bildediagnostikk, blodprøve etc.) bestemmer seg for at pasienten har kreft.​ 




*comment*: Delvise datoer er tillatt. Dersom individet er under ett år gammel, må komplett dato eller som et minimum måned og år oppgis for å muliggjøre presise beregninger av alder, f.eks. ved bruk i beslutningsstøttesystemer. Data registrert eller importert som "alder ved tidspunkt når diagnosen stilles" bør konverteres til en dato ved hjelp av individets fødselsdato.
|
3+a|===== Oncology problem details dips  
| **Multiple primærtumorer** + 
 Type: `Coded text`  | Indikasjon på at det finnes flere primære maligniteter. 
a|

* Multiple primærtumorer +
 `SNOMED-CT:109359008`
| **Beskrivelse** + 
 Type: `Text`  | Beskrivelse av flere primære maligniteter. 
a|

3+a|===== TNM-klassifikasjon klinisk  
| **Primærtumor (T)** + 
 Type: `Coded text`  | Vurdering av primærtumor. 




*comment*: Kodes med en T-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "T1" eller "T3". Fremkommer i "TNM-vurdering" som "T" eller "cT".
a|

* cT0 +
 `SNOMED-CT:1228882005`
* cTis +
 `SNOMED-CT:1228884006`
* cT1 +
 `SNOMED-CT:1228889001`
* cT1a +
 `SNOMED-CT:1228893007`
* cT1b +
 `SNOMED-CT:1228895000`
* cT2 +
 `SNOMED-CT:1228929004`
* cT3 +
 `SNOMED-CT:1228938002`
* cT4 +
 `SNOMED-CT:1228944003`
* cT4a +
 `SNOMED-CT:1228945002`
* cT4b +
 `SNOMED-CT:1228946001`
* cTX +
 `SNOMED-CT:1222604002`
| **Regionale lymfeknuter (N)** + 
 Type: `Coded text`  | Vurdering av hvorvidt det er metastaser i regionale lymfeknuter eller ikke, og i så fall i hvilken grad. 




*comment*: Kodes med en N-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "NX" eller "cN2". Fremkommer i "TNM-vurdering" som "N" eller "cN".
a|

* cN0 +
 `SNOMED-CT:1229967007`
* cN1 +
 `SNOMED-CT:1229973008`
* cN1a +
 `SNOMED-CT:1229975001`
* cN1b +
 `SNOMED-CT:1229976000`
* cN2 +
 `SNOMED-CT:1229978004`
* cN2a +
 `SNOMED-CT:1229981009`
* cN2b +
 `SNOMED-CT:1229982002`
* cN2c +
 `SNOMED-CT:1229983007`
* cN3 +
 `SNOMED-CT:1229984001`
* cN3a +
 `SNOMED-CT:1229985000`
* cN3b +
 `SNOMED-CT:1229986004`
* cNX +
 `SNOMED-CT:1229966003`
| **Fjernmetastase (M)** + 
 Type: `Coded text`  | Vurdering av hvorvidt det er fjernmetastaser eller ikke. 




*comment*: Kodes med en M-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "M1", "cM1a", "M1 PUL" eller or "cM0". Fremkommer i "TNM-vurdering" som "M" eller "cM".
a|

* cM0 +
 `SNOMED-CT:1229901006`
* cM1 +
 `SNOMED-CT:1229903009`
* cMX +
 `SNOMED-CT:27167007`
| **Residiv (r)** + 
 Type: `Boolean`  | Registreres som 'Sann' hvis vurdering er utført for en tilbakevendende kreft etter en kreftfri periode. 




*comment*: Angis ved å legge til prefikset "r" i "TNM-vurdering".
|
| **TNM-vurdering** + 
 Type: `Text`  | Sammentrekning av vurdering av "T", "N" og "M", pluss eventuelle tilleggsvurderinger av "G", "R", "L", "V", prefiks og/eller tillegg der det er passende. 
a|

| **TNM-utgave** + 
 Type: `Coded text`  | TNM-utgaven som er brukt for å bestemme TNM-klassifiseringen. 
a|

* AJCC TNM Versjon 8 +
 `AJCC-TNM-VERSION:Edition8`
* AJCC TNM Versjon 9 +
 `AJCC-TNM-VERSION:Edition9`
3+a|===== TNM-klassifikasjon patologi  
| **Primærtumor (pT)** + 
 Type: `Coded text`  | Vurdering av primærtumor. 




*comment*: Kodes med en T-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "pT1" eller "pT3". Fremkommer i "TNM-vurdering" som "pT".
a|

* pT0 +
 `SNOMED-CT:1228951007`
* pTis +
 `SNOMED-CT:1228953005`
* pT1 +
 `SNOMED-CT:1228957006`
* pT1a +
 `SNOMED-CT:1228959009`
* pT1b +
 `SNOMED-CT:1228962007`
* pT2 +
 `SNOMED-CT:1229852009`
* pT3 +
 `SNOMED-CT:1229859000`
* pT4 +
 `SNOMED-CT:1229864001`
* pT4a +
 `SNOMED-CT:1229865000`
* pT4b +
 `SNOMED-CT:1229866004`
* pTX +
 `SNOMED-CT:1228950008`
| **Regionale lymfeknuter (pN)** + 
 Type: `Coded text`  | Vurdering av hvorvidt det er metastaser i regionale lymfeknuter eller ikke, og i så fall i hvilken grad. 




*comment*: Kodes med en N-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "pNX" eller "pN2". Fremkommer i "TNM-vurdering" som "pN".
a|

* pN0 +
 `SNOMED-CT:1229947003`
* pN1 +
 `SNOMED-CT:1229951001`
* pN1a +
 `SNOMED-CT:1229954009`
* pN1b +
 `SNOMED-CT:1229955005`
* pN2 +
 `SNOMED-CT:1229957002`
* pN2a +
 `SNOMED-CT:1229959004`
* pN2b +
 `SNOMED-CT:1229960009`
* pN2c +
 `SNOMED-CT:1229961008`
* pN3 +
 `SNOMED-CT:1229962001`
* pN3a +
 `SNOMED-CT:1229963006`
* pN3b +
 `SNOMED-CT:1229964000`
* pNX +
 `SNOMED-CT:1229945006`
| **Fjernmetastase (pM)** + 
 Type: `Coded text`  | Vurdering av hvorvidt det er fjernmetastaser eller ikke. 




*comment*: Kodes med en M-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "pM1. Fremkommer i "TNM-vurdering" som "pM".
a|

* pM0 +
 `SNOMED-CT:30893008`
* pM1 +
 `SNOMED-CT:1229916009`
* pMX +
 `SNOMED-CT:27167007`
| **Residiv (r)** + 
 Type: `Boolean`  | Registreres som 'Sann' hvis vurdering er utført for en tilbakevendende kreft etter en kreftfri periode. 




*comment*: Angis ved å legge til prefikset "r" i "TNM-vurdering".
|
| **pTNM-vurdering** + 
 Type: `Text`  | Sammentrekning av vurdering av "pT", "pN" og "pM", pluss eventuelle tilleggsvurderinger av "G", "R", "L", "V", prefiks og/eller tillegg der det er passende. 
a|

| **TNM-utgave** + 
 Type: `Coded text`  | TNM-utgaven som er brukt for å bestemme TNM-klassifiseringen. 
a|

* AJCC TNM Versjon 8 +
 `AJCC-TNM-VERSION:Edition8`
* AJCC TNM Versjon 9 +
 `AJCC-TNM-VERSION:Edition9`
3+a|===== Utredningsmetode regionale lymfeknutemetastaser  
| **Funn** + 
 Type: `Coded text`  | Funnet som støtter utsagnet. 




*comment*: Det anbefales å kode "Funn" med en terminologi, der det er mulig.
a|

* Regional lymfeknutemetastase +
 `SNOMED-CT:399374009`
| **Metode** + 
 Type: `Coded text` (_multiple_) | Typen undersøkelse eller utredning som er utført for å komme fram til funnet. 




*comment*: Metoden bør vurderes kodet med en terminologi der dette er mulig. For eksempel fysisk undersøkelse, røntgen thorax, patologisvar, koloskopi.
a|

* Bildediagnostikk +
 `SNOMED-CT:363679005`
* Cytologi +
 `SNOMED-CT:116147009`
* Biopsi +
 `SNOMED-CT:86273004`
* Fjerning av SN +
 `SNOMED-CT:443497002`
* Reseksjon +
 `SNOMED-CT:65801008`
* Annet +
 `SNOMED-CT:74964007`
* Ukjent +
 `SNOMED-CT:69466000`
| **Spesifier annet** + 
 Type: `Text`  | Fritekstbeskrivelse av annen metode som ble brukt for å komme fram til funnet. 
a|

3+a|===== Utredningsmetode fjernmetastaser  
| **Funn** + 
 Type: `Coded text`  | Funnet som støtter utsagnet. 




*comment*: Det anbefales å kode "Funn" med en terminologi, der det er mulig.
a|

* Fjernmetastase +
 `SNOMED-CT:399409002`
3+a|===== Anatomisk lokalisering  **[multiple]**
| **Navn på kroppssted** + 
 Type: `Coded text` (_mandatory_) | Navngiving av et enkelt fysisk sted enten på eller i menneskekroppen. 




*comment*: Dette dataelementet er det eneste obligatoriske dataelementet i arketypen og bør brukes som det primære dataelementet for registrering av en anatomisk lokalisering. Det er sterkt anbefalt at "Navn på kroppssted" registreres så anatomisk spesifikt som mulig. For eksempel; registrer "øvre øyelokk" heller enn "øyelokk" med "øvre" som kvalifikator; "femte ribben" heller enn "ribben" med en numerisk kvalifikator. Bruk de andre dataelementene for lateralitet, aspekt, region og anatomisk linje for å gi mer detaljer. Dette dataelementet bør kodes med en terminologi som kan assistere beslutningsstøtte dersom mulig - en passende terminologi for bruk her kunne omfatte individuelle konsepter eller lister av prekoordinerte termer. Fritekst bør kun brukes hvis det ikke finnes en passende terminologi. 

Dersom navn på kroppssted er oppgitt i arketypen som denne arketypen er nøstet inn i, kan dette dataelementet være redundant. Imidlertid kan det være fornuftig å dobbeltregistrere navnet på kroppstedet for å støtte semantiske spørringer basert på denne arketypen i stedet for i arketypen den er nøstet inn i.
a|

* Skjelett +
 `SNOMED-CT:113192009`
* Lever +
 `SNOMED-CT:10200004`
* Lunge +
 `SNOMED-CT:39607008`
* CNS (sentralnervesystemet) +
 `SNOMED-CT:21483005`
| **Metode** + 
 Type: `Coded text` (_multiple_) | Typen undersøkelse eller utredning som er utført for å komme fram til funnet. 




*comment*: Metoden bør vurderes kodet med en terminologi der dette er mulig. For eksempel fysisk undersøkelse, røntgen thorax, patologisvar, koloskopi.
a|

* Palpasjon +
 `SNOMED-CT:113011001`
* Bildediagnostikk +
 `SNOMED-CT:363679005`
* Cytologi +
 `SNOMED-CT:116147009`
* Biopsi +
 `SNOMED-CT:86273004`
* Reseksjon +
 `SNOMED-CT:65801008`
* Annet +
 `SNOMED-CT:74964007`
* Ukjent +
 `SNOMED-CT:69466000`
| **Spesifiser annet** + 
 Type: `Text`  | Fritekstbeskrivelse av annen metode som ble brukt for å komme fram til funnet. 
a|

3+a|===== Annen anatomisk lokalisering  
| **Navn på kroppssted** + 
 Type: `Text` (_mandatory_) | Navngiving av et enkelt fysisk sted enten på eller i menneskekroppen. 




*comment*: Dette dataelementet er det eneste obligatoriske dataelementet i arketypen og bør brukes som det primære dataelementet for registrering av en anatomisk lokalisering. Det er sterkt anbefalt at "Navn på kroppssted" registreres så anatomisk spesifikt som mulig. For eksempel; registrer "øvre øyelokk" heller enn "øyelokk" med "øvre" som kvalifikator; "femte ribben" heller enn "ribben" med en numerisk kvalifikator. Bruk de andre dataelementene for lateralitet, aspekt, region og anatomisk linje for å gi mer detaljer. Dette dataelementet bør kodes med en terminologi som kan assistere beslutningsstøtte dersom mulig - en passende terminologi for bruk her kunne omfatte individuelle konsepter eller lister av prekoordinerte termer. Fritekst bør kun brukes hvis det ikke finnes en passende terminologi. 

Dersom navn på kroppssted er oppgitt i arketypen som denne arketypen er nøstet inn i, kan dette dataelementet være redundant. Imidlertid kan det være fornuftig å dobbeltregistrere navnet på kroppstedet for å støtte semantiske spørringer basert på denne arketypen i stedet for i arketypen den er nøstet inn i.
a|

| **Spesifiser annet** + 
 Type: `Text`  | Fritekstbeskrivelse for å ytterligere presisere annen anatomisk lokalisasjon. 




*comment*: For eksempel: Tilgrensende til leppens overgang fra slimhinne til hud; en tatovering dekker nedre halvdel av dette området.
a|

3+a|===== Klinisk grunnlag - morfologi  
| **Morfologisk diagnose** + 
 Type: `Coded text`  | Funnet som støtter utsagnet. 




*comment*: Morfologisk diagnose settes på bakgrunn av kunnskapsbasen som er utviklet for Sarkomkreft. 
a|

* test +
 `no.onk.morfologi.sarkom:1`
| **Merknad morfologisk diagnose** + 
 Type: `Text`  | Fritekstbeskrivelse av funnet. 
a|

| **Diagnosedato (dato utførelse diagnostisk undersøkelse)** + 
 Type: `Date/time`  | Datoen da funnet ble klinisk anerkjent. 




*comment*: For eksempel: Datoen da funnet ble gjort eller gjort tilgjengelig for klinikeren.
|
| **Diagnostisk metode** + 
 Type: `Coded text`  | Typen undersøkelse eller utredning som er utført for å komme fram til funnet. 




*comment*: BNA (18.mars 2025): Er det ikke feil terminologi id på dette feltet? Det står NORPAT, men skal vel være SNOMED-CT?
a|

* Biopsi +
 `SNOMED-CT:86273004`
* Operasjonspreparat +
 `SNOMED-CT:387713003`
* Radiologi +
 `SNOMED-CT:363679005`
* Klinisk +
 `SNOMED-CT:58147004`
| **Type biopsi** + 
 Type: `Coded text`  | Typen undersøkelse eller utredning som er utført for å komme fram til funnet. 




*comment*: BNA (18.mars 2025): Er det ikke feil terminologi id på dette feltet? Det står NORPAT, men skal vel være SNOMED-CT?
a|

* Finnålsaspirasjonscytologi (FNAC) +
 `NORPAT:48635004`
* Nålebiopsi (grovnålsbiopsi/pistolbiopsi) +
 `NORPAT:129249002`
* Åpen biopsi +
 `NORPAT:119283008`
* Pipelle +
 `NORPAT:134279003`
* Uterin abrasio +
 `NORPAT:1082411000202100`
* Eksisjonsbiopsi +
 `NORPAT:8889005`
* Stansebiopsi +
 `NORPAT:68660007`
| **Merknad diagnostisk metode** + 
 Type: `Text`  | Fritekstlig beskrivelse av typen undersøkelse eller utredning som er utført for å komme fram til funnet. 
a|

3+a|===== Prøvemateriale  
| **Preparatnummer** + 
 Type: `Text`  | En unik identifikator av prøvematerialet, som regel tilordnet av laboratoriet. 




*comment*: I noen sammenhenger, som HL7 og IHE, kalt "Accession Identifier", mens et norsk synonym er "Prøvenummer". Prøvebeholdere, for eksempel vakuumglass eller vevskassetter, har egne IDer som registreres i elementet "BeholderID" i arketypen Prøvebeholder.
a|

3+a|===== WHO histologisk grad av bensarkom  
| **Grad** + 
 Type: `Coded text`  |  
a|

* Grad 1 (lavgradig malign)
* Grad 2 (intermediær)
* Grad 3 (høygradig malign)
* Variabel gradering
3+a|===== FNCLCC graderingssystem  
| **Histologisk grad** + 
 Type: `Coded text`  | Vurdering av histologisk grad basert på total skår i FNCLCC graderingssystem. 




*comment*: I klinisk praksis for bløtvevssarkomer, blir 'Histologisk grad'-resultatet fra arketypen ofte gjenbrukt for å fylle ut dataelementet 'Histopatologisk gradering (G)' i arketypene TNM-klassifikasjon klinisk (CLUSTER.tnm) og TNM-klassifikasjon patologi (CLUSTER.tnm-pathological.v1).

a|

* GX
* Grad 1
* Grad 2
* Grad 3
3+a|===== Modifisert NIH-kriterier for GIST  
| **Risikokategori** + 
 Type: `Coded text`  |  
a|

* Meget lav
* Lav
* Intermediær
* Høy risiko
3+a|===== Annen klassifisering sarkom  
| **Klassifisering** + 
 Type: `Coded text`  |  
a|

* Entiteten graderes ikke
* Kan ikke graderes
* Ukjent
* Benign
* Lavgradig
* Høygradig
3+a|===== FIGO stadium for gynekologisk kreft  
| **FIGO stadium** + 
 Type: `Coded text`  | Vurdering av størrelse og utbredelse av tumor, involvering av nærliggende lymfeknuter, og tilstedeværelse eller fravær av fjernmetastaser. 
a|

* Stadium I +
 `no.onk.figo:1`
* Stadium II +
 `no.onk.figo:2`
* Stadium III +
 `no.onk.figo:3`
* Stadium IV +
 `no.onk.figo:4`
3+a|===== Klinisk grunnlag - multifokal  
| **Funn** + 
 Type: `Coded text`  | Funnet som støtter utsagnet. 




*comment*: Det anbefales å kode "Funn" med en terminologi, der det er mulig.
a|

* Growth pattern (observable entity) +
 `SNOMED-CT:404963005`
| **Multifokal tumor** + 
 Type: `Coded text`  | Måling eller verdi knyttet til funnet. 




*comment*: For eksempel mantouxtestresultat.
a|

* Multifokal tumor +
 `SNOMED-CT:399506006`
3+a|===== Problem/diagnose detaljer  
| **Diagnosenavn** + 
 Type: `Coded text`  | Navnet på problem/diagnose 
a|
| **Beskrivelse** + 
 Type: `Text`  | Narrativ beskrivelse av problem/diagnose. 
a|

| **Diagnostisk sikkerhet** + 
 Type: `Coded text`  | Grad av sikkerhet i identifikasjonen av diagnosen. 




*comment*: Hvis et alternativt verdisett er nødvendig, kan disse verdiene legges til DV_TEXT-datatypen i et templat.
a|

* Mistenkt
* Bekreftet
| **Kommentar diagnose/TNM** + 
 Type: `Text`  | Utdypende fritekst om problemet eller diagnosen, som ikke passer i andre felt. 
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da problemet eller diagnosen sist ble oppdatert. 
|
|====
===  *Overordnet behandlingdetaljer*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Behandling for krefttype** + 
 Type: `Coded text` (_mandatory_) | Navnet til intervensjonen. 




*comment*: For eksempel: antibiotika, stråleterapi.
Koding med en terminologi er foretrukket, dersom det er mulig.
a|

* Sarkom +
 `no.onk.kreftgruppering:01`
* Kreft i hode og hals +
 `no.onk.kreftgruppering:02`
* Hjernesvulst +
 `no.onk.kreftgruppering:03`
* Brystkreft +
 `no.onk.kreftgruppering:04`
* Lungekreft +
 `no.onk.kreftgruppering:05`
* Kreft i fordøyelsessystemet +
 `no.onk.kreftgruppering:06`
* Gynekologisk kreft +
 `no.onk.kreftgruppering:07`
* Kreft i nyre og urinveier +
 `no.onk.kreftgruppering:08`
* Benmargs- og blodkreft +
 `no.onk.kreftgruppering:09`
* Lymfom +
 `no.onk.kreftgruppering:10`
* Hudkreft +
 `no.onk.kreftgruppering:11`
* Kreft i mannlige kjønnsorganer +
 `no.onk.kreftgruppering:12`
* Kreft i endokrine kjertler +
 `no.onk.kreftgruppering:13`
* Nevroendokrin kreft +
 `no.onk.kreftgruppering:14`
* Barnekreft +
 `no.onk.kreftgruppering:15`
* Øyekreft +
 `no.onk.kreftgruppering:16`
* Svulst av ukjent opprinnelse / Annet +
 `no.onk.kreftgruppering:17`
| **Intervensjonstype** + 
 Type: `Coded text`  |  




*comment*: 18.mars 2025: Valg av kode er under arbeid. Planlagt møte med HDIR

1	Kreftbehandling
225334002	| Intervention regime (regime/therapy) |
413737006	413737006 | Cancer hospital treatment completed (situation) |



*The type of intervention.

grouping of the interventions.
supertype, her kan man ha f.eks. den overordnede grupperingen. .  (en)
a|

* Kreftbehandling +
 `no.onk.behandlingstype:1`
| **Beskrivelse** + 
 Type: `Text`  | Fritekstlig beskrivelse om intervensjonen. 
a|

| **Behandlingsprotokoll** + 
 Type: `Text`  | Navnet på den kliniske protokollen eller retningslinjen som ligger til grunn for den identifiserte intervensjonen. 
a|

| **Klinisk indikasjon** + 
 Type: `Coded text` (_multiple_) | Symptomet, sykdomstegnet, problemet eller diagnosen som gjør intervensjonen nødvendig. 




*comment*: Koding av "Klinisk indikasjon" med en terminologi er foretrukket, dersom det er mulig.
Dette dataelementet tillater flere forekomster, slik at det kan registrere en eller flere indikasjoner ved behov.
a|

* Primær malign tumor (disorder) +
 `no.onk.kreftgruppering:372087000`
* Residiv av malign tumor (disorder) +
 `no.onk.kreftgruppering:1259237005`
* Metastase malign tumor (disorder) +
 `no.onk.kreftgruppering:128462008`
* Komplikasjon av medisinsk behandling (disorder) +
 `no.onk.kreftgruppering:35688006`
* Annen (qualifier value) +
 `no.onk.kreftgruppering:74964007`
* Primærtumor (ikke malign eller beningn) +
 `no.onk.kreftgruppering:???`
* Tumor (morphologic abnormality) +
 `no.onk.kreftgruppering:108369006`
* Tumor, benign (morphologic abnormality) +
 `no.onk.kreftgruppering:3898006`
* Tumor, malign (morphological abnormality) +
 `no.onk.kreftgruppering:1240414004`
| **Intensjon** + 
 Type: `Coded text`  | Beskrivelse av intensjonen for intervensjonen. 




*comment*: For eksempel: kurativ, palliativ eller preventiv hensikt. 
Koding av "intensjon med en terminologi er foretrukket, dersom det er mulig.
Dette dataelementet tillater flere forekomster, slik at det er mulig å registrere en eller flere alternativer ved behov.
a|

* Kurativt +
 `no.onk.behandlingsintensjon:K1`
* Aktiv overvåkning +
 `no.onk.behandlingsintensjon:K2`
* Livsforlengende - ikke kurativ +
 `no.onk.behandlingsintensjon:K3`
* Symptomlindrende - ikke kurativ +
 `no.onk.behandlingsintensjon:K4`
* Lokal kontroll - ikke kurativ +
 `no.onk.behandlingsintensjon:K5`
* Ukjent +
 `no.onk.behandlingsintensjon:K6`
| **Treatment line** + 
 Type: `Coded text` (_multiple_) | Kategorien av den identifiserte intervensjonen. 




*comment*: For eksempel: neoadjuvant, concomitant (samtidig) og adjuvant.
a|

* First line treatment +
 `SNOMED-CT:708255002`
* Second line treatment +
 `SNOMED-CT:708256001`
* Third line treatment +
 `SNOMED-CT:708257005`
| **Start behandlingsforløp** + 
 Type: `Date/time`  | Datoen da den identifiserte intervensjon startet. 
|
| **Stopp behandlingsforløp** + 
 Type: `Date/time`  | Datoen da en identifiserte intervensjon ble fullført eller stoppet før fullføring. 
|
| **Fullføringsstatus** + 
 Type: `Coded text`  | Om intervensjonen ble gjennomført som planlagt eller ikke. 
a|

* Fullført
* Ikke fullført
| **Årsak til ikke fullført** + 
 Type: `Text`  | Beskrivelsen av årsaken til at en intervensjon ikke ble fullført (ufullstendig). 




*comment*: Koding med en terminologi er foretrukket, dersom det er mulig.
a|

| **Resultatkategori** + 
 Type: `Text`  | Kategori av resultatet for intervensjonen 




*comment*: For eksempel: vellykket, ikke vellykket, usikkert.
Koding med en terminologi er foretrukket, dersom det er mulig.
a|

* Vellykket i henhold til intensjon
* Ikke vellykket i henhold til intensjon
| **Årsak til resultatkategori** + 
 Type: `Text`  | Beskrivelse av årsaken bak resultatkategorien. 




*comment*: For eksempel: resistens mot medikament.
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da denne intervensjonssoppsummeringen sist ble oppdatert. 
|
|====
===  *Intervensjonssammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Intervensjon navn** + 
 Type: `Coded text` (_mandatory_) | Navnet til intervensjonen. 




*comment*: *For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
a|

* Eksisjon (reseksjon) +
 `NKPK - liste må bearbeides:65801008`
* Reeksisjon (ny utskjæring) +
 `NKPK - liste må bearbeides:65854006`
* Amputasjon +
 `NKPK - liste må bearbeides:81723002`
* Curettage +
 `NKPK - liste må bearbeides:68688001`
* Revisjon (gjentakelse av tidligere prosedyre for å korrigere eller forbedre resultat) +
 `NKPK - liste må bearbeides:118635009`
* Annet +
 `NKPK - liste må bearbeides:74964007`
| **Intervensjonstype** + 
 Type: `Coded text`  | *The type of intervention.

grouping of the interventions.
supertype, her kan man ha f.eks. den overordnede grupperingen. .  (en) 




*comment*: Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
a|

* Kirurgisk inngrep +
 `SNOMED-CT:387713003`
| **Beskrivelse** + 
 Type: `Text`  | Fritekstlig beskrivelse om intervensjonen. 
a|

| **Protokollnavn** + 
 Type: `Text`  | Navnet på den kliniske protokollen eller retningslinjen som ligger til grunn for den identifiserte intervensjonen. 




*comment*: Designkommentar:
arver fra toppnivå
a|

| **Indikasjon for behandling/behandlingsgrunnlag** + 
 Type: `Text` (_multiple_) | Symptomet, sykdomstegnet, problemet eller diagnosen som gjør intervensjonen nødvendig. 




*comment*: Koding av "Klinisk indikasjon" med en terminologi er foretrukket, dersom det er mulig.
Dette dataelementet tillater flere forekomster, slik at det kan registrere en eller flere indikasjoner ved behov.
a|

| **Terapautisk rolle** + 
 Type: `Coded text` (_multiple_) | *The position of this intervention in relation to other interventions in the overall treatment plan. For example: Main vs additional, First line vs second line, or neoadjuvant vs adjuvant (en) 




*comment*: *For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
a|

* Hovedbehandling +
 `no.onk.behandling.kategori:1`
| **Intervensjonsdato** + 
 Type: `Date/time`  | Datoen da den identifiserte intervensjon startet. 
|
3+a|===== Anatomisk lokalisering  **[multiple]**
| **Navn på kroppssted** + 
 Type: `Text` (_mandatory_) | Navngiving av et enkelt fysisk sted enten på eller i menneskekroppen. 




*comment*: Dette dataelementet er det eneste obligatoriske dataelementet i arketypen og bør brukes som det primære dataelementet for registrering av en anatomisk lokalisering. Det er sterkt anbefalt at "Navn på kroppssted" registreres så anatomisk spesifikt som mulig. For eksempel; registrer "øvre øyelokk" heller enn "øyelokk" med "øvre" som kvalifikator; "femte ribben" heller enn "ribben" med en numerisk kvalifikator. Bruk de andre dataelementene for lateralitet, aspekt, region og anatomisk linje for å gi mer detaljer. Dette dataelementet bør kodes med en terminologi som kan assistere beslutningsstøtte dersom mulig - en passende terminologi for bruk her kunne omfatte individuelle konsepter eller lister av prekoordinerte termer. Fritekst bør kun brukes hvis det ikke finnes en passende terminologi. 

Dersom navn på kroppssted er oppgitt i arketypen som denne arketypen er nøstet inn i, kan dette dataelementet være redundant. Imidlertid kan det være fornuftig å dobbeltregistrere navnet på kroppstedet for å støtte semantiske spørringer basert på denne arketypen i stedet for i arketypen den er nøstet inn i.
a|

| **Spesifikt sted** + 
 Type: `Text` (_multiple_) | Ytterligere detaljer gitt ved hjelp av en spesifikk region eller et punkt på eller i det spesifiserte kroppsstedet. 




*comment*: Brukes til å øke presisjonen ved spesifisering av kroppsstedet, dersom påkrevd. For eksempel den øvre høyre kvadranten eller McBurneys punkt på bukveggen, eller interfalangealleddet på stortåen. Dersom dataelementet "Navn på kroppssted" er registrert ved hjelp av prekoordinerte termer som omfatter det spesifikke stedet er dette dataelementet overflødig. I de fleste tilfeller vil dette være ett enkelt sted på kroppen. Dataelementet åpner for flere forekomster i de sjeldne tilfellene der man trenger å angi et spesifikt anatomisk sted som omfatter to eller flere sammenhengende spesifikke steder. For eksempel for å beskrive det spesifikke stedet en svulst strekker seg over andre, tredje og fjerde ribben.
a|

| **Kroppsside** + 
 Type: `Coded text`  | Den identifiserte kroppssiden. 




*comment*: Hvis den identifiserte kroppssiden ikke har noen lateralitet, bør dette datalementet stå tomt. Hvis dataelementet "Navn på kroppsted" bruker prekoordinerte termer som inkluderer lateralitet, er dette dataelementet overflødig.
a|

* Venstre
* Høyre
| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da denne intervensjonssoppsummeringen sist ble oppdatert. 
|
|====
===  *Intervensjonssammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Intervensjon navn** + 
 Type: `Coded text` (_mandatory_) | Navnet til intervensjonen. 




*comment*: *For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
a|

* Kjemoterapi - Medikamentell +
 `SNOMED-CT:367336001`
* Målrettet - Medikamentell +
 `SNOMED-CT:347531000202105`
* Immunterapi for kreft - Medikamentell +
 `SNOMED-CT:64644003`
* Hormonterapi – Medikamentell +
 `SNOMED-CT:169413002`
| **Intervensjonstype** + 
 Type: `Coded text`  | *The type of intervention.

grouping of the interventions.
supertype, her kan man ha f.eks. den overordnede grupperingen. .  (en) 




*comment*: Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
a|

* Medikamentell behandling (procedure) +
 `SNOMED-CT:416608005`
| **Beskrivelse** + 
 Type: `Text`  | Fritekstlig beskrivelse om intervensjonen. 
a|

| **Protokollnavn** + 
 Type: `Text`  | Navnet på den kliniske protokollen eller retningslinjen som ligger til grunn for den identifiserte intervensjonen. 
a|

| **Terapautisk rolle** + 
 Type: `Coded text` (_multiple_) | *The position of this intervention in relation to other interventions in the overall treatment plan. For example: Main vs additional, First line vs second line, or neoadjuvant vs adjuvant (en) 




*comment*: *For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
a|

* Hovedbehandling +
 `no.onk.behandling.kategori:1`
| **Start dato** + 
 Type: `Date/time`  | Datoen da den identifiserte intervensjon startet. 
|
| **Stopp dato** + 
 Type: `Date/time`  | Datoen da en identifiserte intervensjon ble fullført eller stoppet før fullføring. 
|
| **Fullføringsstatus** + 
 Type: `Coded text`  | Om intervensjonen ble gjennomført som planlagt eller ikke. 
a|

* Fullført
* Ikke fullført
| **Årsak til ikke fullført** + 
 Type: `Text`  | Beskrivelsen av årsaken til at en intervensjon ikke ble fullført (ufullstendig). 




*comment*: Koding med en terminologi er foretrukket, dersom det er mulig.
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da denne intervensjonssoppsummeringen sist ble oppdatert. 
|
|====
===  *Legemiddelsammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Navn på kur/medikament** + 
 Type: `Text` (_mandatory_) | Navn på legemiddel eller gruppe av legemidler. 




*comment*: Navn på legemiddel kan representeres som en generisk substans, handelsnavn, gruppe eller klasse av legemidler. Det anbefales å kode "Navn på legemiddel" med en terminologi om mulig, slik at det kan brukes for eksempel i beslutningsstøtte. Fritekst bør bare benyttes der det ikke finnes en passende terminologi.
For eksempel: '"Adriamycin"; "doxorubicin" eller "anthracycliner"; "Fosamax", "alendronsyre" eller "bifosonater".
a|

| **Startdato for bruk** + 
 Type: `Date/time`  | Datoen da legemiddelet først ble administrert. 




*comment*: Kan være en deldato, for eksempel kun årstall.
|
| **Kumulativ mengde** + 
 Type: `Quantity`  | Samlet mengde av legemiddelet brukt over individets livstid. 




*comment*: For eksempel: monitorering av kumulativ mengde av doxorubicin.
Kan regnes ut manuelt eller utledes via ulike kilder, som for eksempel kurvesystemet eller andre deler av den elektroniske pasientjournalen.
a|

Valid units: +

* mg
* ug
* [iU]
* ng
| **Sluttdato for bruk** + 
 Type: `Date/time`  | Datoen da legemiddelet sist ble administrert. 




*comment*: Kan være en deldato, for eksempel kun årstall.
|
| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da legemiddelsammendraget sist ble oppdatert. 
|
|====
===  *Intervensjonssammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Intervensjon navn** + 
 Type: `Coded text` (_mandatory_) | Navnet til intervensjonen. 




*comment*: *For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
a|

* Stråleterapi (alle typer) +
 `velge kodeverk:1287742003`
* Fotonterapi - Stråle (ekstern) +
 `velge kodeverk:1156506007`
* Protonterapi -Stråle (ekstern) +
 `velge kodeverk:169314007`
* Elektronterapi - Stråle (ekstern) +
 `velge kodeverk:45643008`
* Brakyterapi - Stråle (intern) +
 `velge kodeverk:152198000`
* Radioisotope/systemisk radionuklidebehandling - Stråle (intern) +
 `velge kodeverk:399315003`
* Partikkelstråleterapi (karbon eller proton) +
 `velge kodeverk:WEOC`
* Karbonterapi +
 `velge kodeverk:WEOC10`
* Protonterapi (NKPK) +
 `velge kodeverk:WEOC00`
* Ekstern stråleterapi +
 `velge kodeverk:WEOA`
* Brakyterapi +
 `velge kodeverk:WEOB`
* Stråleterapi +
 `velge kodeverk:WE`
| **Intervensjonstype** + 
 Type: `Coded text`  | *The type of intervention.

grouping of the interventions.
supertype, her kan man ha f.eks. den overordnede grupperingen. .  (en) 




*comment*: Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
a|

* Radiotherapy (procedure) +
 `SNOMED-CT:1287742003`
| **Beskrivelse av stråleintervensjonen** + 
 Type: `Text`  | Fritekstlig beskrivelse om intervensjonen. 
a|

| **Protokollnavn** + 
 Type: `Text`  | Navnet på den kliniske protokollen eller retningslinjen som ligger til grunn for den identifiserte intervensjonen. 
a|

| **Terapautisk rolle** + 
 Type: `Coded text` (_multiple_) | *The position of this intervention in relation to other interventions in the overall treatment plan. For example: Main vs additional, First line vs second line, or neoadjuvant vs adjuvant (en) 




*comment*: *For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
a|

* Hovedbehandling +
 `no.onk.behandling.kategori:1`
| **Dato første fraksjon** + 
 Type: `Date/time`  | Datoen da den identifiserte intervensjon startet. 
|
| **Dato siste fraksjon** + 
 Type: `Date/time`  | Datoen da en identifiserte intervensjon ble fullført eller stoppet før fullføring. 
|
| **Fullføringsstatus** + 
 Type: `Coded text`  | Om intervensjonen ble gjennomført som planlagt eller ikke. 
a|

* Fullført
* Ikke fullført
| **Årsak til ikke fullført** + 
 Type: `Text`  | Beskrivelsen av årsaken til at en intervensjon ikke ble fullført (ufullstendig). 




*comment*: Koding med en terminologi er foretrukket, dersom det er mulig.
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da denne intervensjonssoppsummeringen sist ble oppdatert. 
|
| **Stråleterapi course ID** + 
 Type: `Choice`  | An identifier for the invention as a whole. 
a|
_Multiple data types allowed_
|_SubTypes_ | |
| Type: `Identifier` |
|
| Type: `Text` |
a|

|====
===  *Intervensjonssammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Intervensjon navn** + 
 Type: `Coded text` (_mandatory_) | Navnet til intervensjonen. 




*comment*: *For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
a|

* Eksisjon (reseksjon) +
 `NKPK - liste må bearbeides:65801008`
* Reeksisjon (ny utskjæring) +
 `NKPK - liste må bearbeides:65854006`
* Amputasjon +
 `NKPK - liste må bearbeides:81723002`
* Curettage +
 `NKPK - liste må bearbeides:68688001`
* Revisjon (gjentakelse av tidligere prosedyre for å korrigere eller forbedre resultat) +
 `NKPK - liste må bearbeides:118635009`
* Annet +
 `NKPK - liste må bearbeides:74964007`
| **Intervensjonstype** + 
 Type: `Coded text`  | *The type of intervention.

grouping of the interventions.
supertype, her kan man ha f.eks. den overordnede grupperingen. .  (en) 




*comment*: Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
a|

* Kirurgisk inngrep +
 `SNOMED-CT:387713003`
| **Beskrivelse** + 
 Type: `Text`  | Fritekstlig beskrivelse om intervensjonen. 
a|

| **Protokollnavn** + 
 Type: `Text`  | Navnet på den kliniske protokollen eller retningslinjen som ligger til grunn for den identifiserte intervensjonen. 




*comment*: Designkommentar:
arver fra toppnivå
a|

| **Terapautisk rolle** + 
 Type: `Coded text` (_multiple_) | *The position of this intervention in relation to other interventions in the overall treatment plan. For example: Main vs additional, First line vs second line, or neoadjuvant vs adjuvant (en) 




*comment*: *For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
a|

* Adjuvant hensikt +
 `SNOMED-CT:373846009`
* Neoadjuvant hensikt +
 `SNOMED-CT:373847000`
* Konkomitant (adjunkt) hensikt) +
 `SNOMED-CT:421974008`
| **Intervensjonsdato** + 
 Type: `Date/time`  | Datoen da den identifiserte intervensjon startet. 
|
3+a|===== Anatomisk lokalisering  **[multiple]**
| **Navn på kroppssted** + 
 Type: `Text` (_mandatory_) | Navngiving av et enkelt fysisk sted enten på eller i menneskekroppen. 




*comment*: Dette dataelementet er det eneste obligatoriske dataelementet i arketypen og bør brukes som det primære dataelementet for registrering av en anatomisk lokalisering. Det er sterkt anbefalt at "Navn på kroppssted" registreres så anatomisk spesifikt som mulig. For eksempel; registrer "øvre øyelokk" heller enn "øyelokk" med "øvre" som kvalifikator; "femte ribben" heller enn "ribben" med en numerisk kvalifikator. Bruk de andre dataelementene for lateralitet, aspekt, region og anatomisk linje for å gi mer detaljer. Dette dataelementet bør kodes med en terminologi som kan assistere beslutningsstøtte dersom mulig - en passende terminologi for bruk her kunne omfatte individuelle konsepter eller lister av prekoordinerte termer. Fritekst bør kun brukes hvis det ikke finnes en passende terminologi. 

Dersom navn på kroppssted er oppgitt i arketypen som denne arketypen er nøstet inn i, kan dette dataelementet være redundant. Imidlertid kan det være fornuftig å dobbeltregistrere navnet på kroppstedet for å støtte semantiske spørringer basert på denne arketypen i stedet for i arketypen den er nøstet inn i.
a|

| **Spesifikt sted** + 
 Type: `Text` (_multiple_) | Ytterligere detaljer gitt ved hjelp av en spesifikk region eller et punkt på eller i det spesifiserte kroppsstedet. 




*comment*: Brukes til å øke presisjonen ved spesifisering av kroppsstedet, dersom påkrevd. For eksempel den øvre høyre kvadranten eller McBurneys punkt på bukveggen, eller interfalangealleddet på stortåen. Dersom dataelementet "Navn på kroppssted" er registrert ved hjelp av prekoordinerte termer som omfatter det spesifikke stedet er dette dataelementet overflødig. I de fleste tilfeller vil dette være ett enkelt sted på kroppen. Dataelementet åpner for flere forekomster i de sjeldne tilfellene der man trenger å angi et spesifikt anatomisk sted som omfatter to eller flere sammenhengende spesifikke steder. For eksempel for å beskrive det spesifikke stedet en svulst strekker seg over andre, tredje og fjerde ribben.
a|

| **Kroppsside** + 
 Type: `Coded text`  | Den identifiserte kroppssiden. 




*comment*: Hvis den identifiserte kroppssiden ikke har noen lateralitet, bør dette datalementet stå tomt. Hvis dataelementet "Navn på kroppsted" bruker prekoordinerte termer som inkluderer lateralitet, er dette dataelementet overflødig.
a|

* Venstre
* Høyre
| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da denne intervensjonssoppsummeringen sist ble oppdatert. 
|
|====
===  *Intervensjonssammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Intervensjon navn** + 
 Type: `Coded text` (_mandatory_) | Navnet til intervensjonen. 




*comment*: *For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
a|

* Kjemoterapi - Medikamentell +
 `SNOMED-CT:367336001`
* Målrettet - Medikamentell +
 `SNOMED-CT:347531000202105`
* Immunterapi for kreft - Medikamentell +
 `SNOMED-CT:64644003`
* Hormonterapi – Medikamentell +
 `SNOMED-CT:169413002`
| **Intervensjonstype** + 
 Type: `Coded text`  | *The type of intervention.

grouping of the interventions.
supertype, her kan man ha f.eks. den overordnede grupperingen. .  (en) 




*comment*: Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
a|

* Medikamentell behandling (procedure) +
 `SNOMED-CT:416608005`
| **Beskrivelse** + 
 Type: `Text`  | Fritekstlig beskrivelse om intervensjonen. 
a|

| **Protokollnavn** + 
 Type: `Text`  | Navnet på den kliniske protokollen eller retningslinjen som ligger til grunn for den identifiserte intervensjonen. 
a|

| **Terapautisk rolle** + 
 Type: `Coded text` (_multiple_) | *The position of this intervention in relation to other interventions in the overall treatment plan. For example: Main vs additional, First line vs second line, or neoadjuvant vs adjuvant (en) 




*comment*: *For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
a|

* Adjuvant hensikt +
 `SNOMED-CT:373846009`
* Neoadjuvant hensikt +
 `SNOMED-CT:373847000`
* Konkomitant (adjunkt) hensikt) +
 `SNOMED-CT:421974008`
| **Start dato** + 
 Type: `Date/time`  | Datoen da den identifiserte intervensjon startet. 
|
| **Stopp dato** + 
 Type: `Date/time`  | Datoen da en identifiserte intervensjon ble fullført eller stoppet før fullføring. 
|
| **Fullføringsstatus** + 
 Type: `Coded text`  | Om intervensjonen ble gjennomført som planlagt eller ikke. 
a|

* Fullført
* Ikke fullført
| **Årsak til ikke fullført** + 
 Type: `Text`  | Beskrivelsen av årsaken til at en intervensjon ikke ble fullført (ufullstendig). 




*comment*: Koding med en terminologi er foretrukket, dersom det er mulig.
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da denne intervensjonssoppsummeringen sist ble oppdatert. 
|
|====
===  *Legemiddelsammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Navn på kur/medikament** + 
 Type: `Text` (_mandatory_) | Navn på legemiddel eller gruppe av legemidler. 




*comment*: Navn på legemiddel kan representeres som en generisk substans, handelsnavn, gruppe eller klasse av legemidler. Det anbefales å kode "Navn på legemiddel" med en terminologi om mulig, slik at det kan brukes for eksempel i beslutningsstøtte. Fritekst bør bare benyttes der det ikke finnes en passende terminologi.
For eksempel: '"Adriamycin"; "doxorubicin" eller "anthracycliner"; "Fosamax", "alendronsyre" eller "bifosonater".
a|

| **Startdato for bruk** + 
 Type: `Date/time`  | Datoen da legemiddelet først ble administrert. 




*comment*: Kan være en deldato, for eksempel kun årstall.
|
| **Kumulativ mengde** + 
 Type: `Quantity`  | Samlet mengde av legemiddelet brukt over individets livstid. 




*comment*: For eksempel: monitorering av kumulativ mengde av doxorubicin.
Kan regnes ut manuelt eller utledes via ulike kilder, som for eksempel kurvesystemet eller andre deler av den elektroniske pasientjournalen.
a|

Valid units: +

* mg
* ug
* [iU]
* ng
| **Sluttdato for bruk** + 
 Type: `Date/time`  | Datoen da legemiddelet sist ble administrert. 




*comment*: Kan være en deldato, for eksempel kun årstall.
|
| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da legemiddelsammendraget sist ble oppdatert. 
|
|====
===  *Intervensjonssammendrag*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **Intervensjon navn** + 
 Type: `Coded text` (_mandatory_) | Navnet til intervensjonen. 




*comment*: *For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
a|

* Stråleterapi (alle typer) +
 `velge kodeverk:1287742003`
* Fotonterapi - Stråle (ekstern) +
 `velge kodeverk:1156506007`
* Protonterapi -Stråle (ekstern) +
 `velge kodeverk:169314007`
* Elektronterapi - Stråle (ekstern) +
 `velge kodeverk:45643008`
* Brakyterapi - Stråle (intern) +
 `velge kodeverk:152198000`
* Radioisotope/systemisk radionuklidebehandling - Stråle (intern) +
 `velge kodeverk:399315003`
* Partikkelstråleterapi (karbon eller proton) +
 `velge kodeverk:WEOC`
* Karbonterapi +
 `velge kodeverk:WEOC10`
* Protonterapi (NKPK) +
 `velge kodeverk:WEOC00`
* Ekstern stråleterapi +
 `velge kodeverk:WEOA`
* Brakyterapi +
 `velge kodeverk:WEOB`
* Stråleterapi +
 `velge kodeverk:WE`
| **Intervensjonstype** + 
 Type: `Coded text`  | *The type of intervention.

grouping of the interventions.
supertype, her kan man ha f.eks. den overordnede grupperingen. .  (en) 




*comment*: Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
a|

* Radiotherapy (procedure) +
 `SNOMED-CT:1287742003`
| **Beskrivelse av stråleintervensjonen** + 
 Type: `Text`  | Fritekstlig beskrivelse om intervensjonen. 
a|

| **Protokollnavn** + 
 Type: `Text`  | Navnet på den kliniske protokollen eller retningslinjen som ligger til grunn for den identifiserte intervensjonen. 
a|

| **Terapautisk rolle** + 
 Type: `Coded text` (_multiple_) | *The position of this intervention in relation to other interventions in the overall treatment plan. For example: Main vs additional, First line vs second line, or neoadjuvant vs adjuvant (en) 




*comment*: *For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
a|

* Adjuvant hensikt +
 `SNOMED-CT:373846009`
* Neoadjuvant hensikt +
 `SNOMED-CT:373847000`
* Konkomitant (adjunkt) hensikt) +
 `SNOMED-CT:421974008`
| **Dato første fraksjon** + 
 Type: `Date/time`  | Datoen da den identifiserte intervensjon startet. 
|
| **Dato siste fraksjon** + 
 Type: `Date/time`  | Datoen da en identifiserte intervensjon ble fullført eller stoppet før fullføring. 
|
| **Fullføringsstatus** + 
 Type: `Coded text`  | Om intervensjonen ble gjennomført som planlagt eller ikke. 
a|

* Fullført
* Ikke fullført
| **Årsak til ikke fullført** + 
 Type: `Text`  | Beskrivelsen av årsaken til at en intervensjon ikke ble fullført (ufullstendig). 




*comment*: Koding med en terminologi er foretrukket, dersom det er mulig.
a|

| **Sist oppdatert** + 
 Type: `Date/time`  | Datoen da denne intervensjonssoppsummeringen sist ble oppdatert. 
|
| **Stråleterapi course ID** + 
 Type: `Choice`  | An identifier for the invention as a whole. 
a|
_Multiple data types allowed_
|_SubTypes_ | |
| Type: `Identifier` |
|
| Type: `Text` |
a|

|====
===  *Kartleggingsspørsmål av uønskede effekter ved behandling*


undefined


[options="header","stretch", cols="20,50,30"]
|====
|Data item | Description | Allowed values
| **time** + 
 Type: `Date/time` (_mandatory_) | `OBSERVATION.EVENT.time` - Time of this Observation event. If the width is non-zero, it is the time point of the trailing edge of the event. 
|
| **Kartleggingsformål** + 
 Type: `Coded text`  | Konteksten eller årsaken for kartleggingen. 




*comment*: Dette dataelementet er ment for å sette en kontekst for spørsmålene om man senere ønsker å gjøre spørringer på dataene. Det er ikke forventet at dette dataelementet skal være synlig for en bruker av skjemaet, men kun tilgjengelig i de lagrede dataene. 
For eksempel: "Pre operativ screening" eller navnet på det faktiske spørreskjemaet.
a|

* CTCAE +
 `no.onk.kart.tidligere_komplikasjoner_kreftbehandling:1`
| **Har tidligere kreftbehandling gitt noen uønskede effekter?** + 
 Type: `Choice` (_multiple_) | Finnes det noen tidligere symptomer eller sykdomstegn som er innenfor kartleggingsformålet? 




*comment*: Navnet på dataelementet kan omformuleres til det spesifikke spørsmålet i et templat eller brukergrensesnitt. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
a|
_Multiple data types allowed_
|_SubTypes_ | |
| Type: `Coded text` |
a|

* Ja
* Nei
* Ukjent
| Type: `Text` |
a|

| Type: `Boolean` |
|
3+a|===== Common Terminology Criteria for Adverse Events (CTCAE)  **[multiple]**
| **Kategori** + 
 Type: `Coded text`  | Kategorien innenfor MedDRA System Organ Class (SOC) som er knyttet til CTCAE Term (LTT). 




*comment*: Dette elementet identifiserer et anatomisk eller fysiologisk system, etiologi eller formål.


a|

* Blood and lymphatic system disorders +
 `MEDRA:1001`
| **Term** + 
 Type: `Coded text` (_mandatory_) | Navnet på sykdomstegnet, symptomet eller sykdommen som er observert, registrert som en MedDRA Lowest Level Term (LLT). 




*comment*: Dette elementet kan mappes til den korresponderende MedDRA-koden.
a|

* X +
 `MEDRA:X`
| **Kategori for grad** + 
 Type: `Ordinal` (_mandatory_) | Kategorien som representerer alvorlighetsgraden av den uønskede hendelsen. 




*comment*: Den kliniske beskrivelsen for hver "Kategori for grad" er dokumentert i den publiserte spesifikasjonen av CTCAE v5.0. Grad 0 har ikke vært i bruk siden CTCAE v2, men er tatt med for å kunne brukes for alle versjoner av CTCAE.
a|
* [0] Grad 0 +
 `local:at0021`
* [1] Grad 1 +
 `local:at0015`
* [2] Grad 2 +
 `local:at0016`
* [3] Grad 3 +
 `local:at0017`
* [4] Grad 4 +
 `local:at0018`
* [5] Grad 5 +
 `local:at0019`
| **Beskrivelse av grad** + 
 Type: `Coded text`  | Termen eller frasen som representerer alvorlighetsgraden til den uønskede hendelsen. 




*comment*: Dette elementet er en plassholder for term eller frase som tilhører en identifisert grad. I de fleste implementasjonene vil det bli utfylt via en eksterne kilde, som en CTCAE kunnskapsbase eller en annen kilde, under kjøring av dataprogrammet (run-time).
a|

* A +
 `CTCAETERM:A`
| **CTCAE- versjon** + 
 Type: `Text`  | Den versjonen av CTCAE-terminologien som er brukt. 
a|

|====


== Archetype provenance
[options="header","stretch", cols="33,33,33"]
|===
|Internal | Candidate | External
| Internal archetypes which are not intended to be shared | Internal archetypes which are candidates for external publication| Archetypes published or managed externally
| **Total: 0     Percent: (%)** | **Total: 0     Percent: (%)** | **Total: 0     Percent: (%)**
a|
a|
a|
===|
