= Kartlegging omsorgsansvar


== Metadata


TemplateId:: omsorgsansvar_kartlegging


Archetype:: openEHR-EHR-OBSERVATION.social_context_screening.v1




:toc:




== Kartlegging omsorgsansvar
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging omsorgsansvar* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.social_context_screening.v1_
|at0034| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Kartlegging av om individet har omsorgsansvar (no.onk.sosiale_forhold: OA)


Dette dataelementet er ment for å sette en kontekst for samlingen av spørsmål/svar til bruk senere for å gjøre spørringer på dataene. Det er ikke forventet at dette dataelementet skal være synlig for en bruker av skjemaet, men kun tilgjengelig i de lagrede dataene.
5+a|*Omsorgsperson for barn under 18 år* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Ansvarlig for barn under 18 år (no.onk.sosiale_forhold: U18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Har pasienten ansvar for barn under 18 år?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 


I templat vil navnet på dataelementet normalt omformuleres til det spesifikke spørsmålet. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
5+a|*Barn som pårørende* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Barn som pårørende (no.onk.sosiale_forhold: BPU18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Finnes det barn som pårørende?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 


I templat vil navnet på dataelementet normalt omformuleres til det spesifikke spørsmålet. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
|at0025| 0..1| DV_TEXT | Kommentar
a|
5+a|*Omsorgsperson for personer over 18 år* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Ansvarlig for barn/andre over 18 år (no.onk.sosiale_forhold: O18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Har pasienten ansvar for egne barn/andre over 18 år?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 


I templat vil navnet på dataelementet normalt omformuleres til det spesifikke spørsmålet. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
|====