= Biomarkør 

Biomarkører er utpekt som viktige datapunkt ved oppfølging av kreftpasientene. Disse skal hentes ut og sendes over til protonregisteret. I det følgnende beskrives nærmere hva som menes med biomarkører. 

== Hva er en biomarkør? 
I følge Store Norske Leksikon er biomarkører _stoffer eller molekyler som kan måles eller påvises i en kropp eller celle, og som forteller noe om en underliggende tilstand._. 

En genetisk markør defineres som _gen eller en DNA-sekvens med kjent posisjon på et kromosom som brukes til å identifisere et individ eller en art_. Videre er det slik at genetiske markører kan benyttes i diagnostikk. 


Helsedirektoratet skriver om biomarkører i handlingsprogrammet for prostatakreft. Der står det: 

> En biomarkør er et stoff eller et molekyl som kan analyseres en kroppsvæske eller vev, og som ut fra markørens tilstedeværelse sier noe om en tilstand i kroppen. I praksis kombineres ofte to eller flere markører før viktige valg om utredning og/eller behandling. Det er utviklet nomogrammer og kalkulatorer som kan være til hjelp for å estimere individuell risiko i en konkret situasjon.

> Biomarkører kan anvendes alene eller i kombinasjon på forskjellige tidspunkter under utredning og behandling av prostatakreft. Ett eksempel er risikostratifsering basert på PSA, ISUP-grad gruppe og TNM-stadium.

Se mer her: https://www.helsedirektoratet.no/retningslinjer/prostatakreft-handlingsprogram/markorer/biomarkorer-blod-urin-vev 

== Hvordan modellere biomarkører? 
Som det kommer frem av det overnevnte kan det sies at biomarkører er en veldig generell definisjon. Datateknisk vil det være stor variasjon i hvordan en biomarkør defineres. Likevel må vi gjøre et forsøk på å gruppere dette. Flere modeller kan være aktuelle. Her prøves følgende metodikk ut: 

Kategorier av biomarkører: 

Biokjemiske:: Det vil si tradisjonelle biokjemiske marører (som PSA) som måles på en lab og typisk er representert i lab-arket i journalen 

Genetiske:: Det vil angivelse av definerte genetiske forekomster og hvor resultatet er _Ja - den finnes_  eller _Nei - den finnes ikke_. 

Graderinger/stratifiseringer:: Som f.eks. TNM stadium, ISUP gradering eller annen gradert skala. 


== Biokjemiske 

Analysenavn

== Liste med markører fra OUS 
Denne listen er generert av ChatGpt frs Ous webside 


[options="header"]
|===
| Gen-ID | Gen-navn
| APC    | ADENOMATOUS POLYPOSIS COLI
| ATM    | ATAXIA-TELANGIECTASIA MUTATED
| BAP1   | BRCA1 ASSOCIATED PROTEIN 1
| BMPR1A | BONE MORPHOGENETIC PROTEIN RECEPTOR TYPE 1A
| BRCA1  | BREAST CANCER GENE 1
| BRCA2  | BREAST CANCER GENE 2
| CDH1   | CADHERIN 1
| CDKN2A | CYCLIN-DEPENDENT KINASE INHIBITOR 2A
| CHEK2  | CHECKPOINT KINASE 2
| EPCAM  | EPITHELIAL CELL ADHESION MOLECULE
| FH     | FUMARATE HYDRATASE
| FLCN   | FOLLICULIN
| MEN1   | MULTIPLE ENDOCRINE NEOPLASIA TYPE 1
| MLH1   | MUTL HOMOLOG 1
| MSH2   | MUTS HOMOLOG 2
| MSH6   | MUTS HOMOLOG 6
| MUTYH  | MUTY DNA GLYCOSYLASE
| NBN    | NIBRIN
| NF1    | NEUROFIBROMIN 1
| PALB2  | PARTNER AND LOCALIZER OF BRCA2
| PMS2   | PMS1 HOMOLOG 2
| PTEN   | PHOSPHATASE AND TENSIN HOMOLOG
| RAD51C | RAD51 PARALOG C
| RAD51D | RAD51 PARALOG D
| RB1    | RETINOBLASTOMA 1
| RET    | RET PROTO-ONCOGENE
| SDHB   | SUCCINATE DEHYDROGENASE COMPLEX SUBUNIT B
| SDHD   | SUCCINATE DEHYDROGENASE COMPLEX SUBUNIT D
| SMAD4  | SMAD FAMILY MEMBER 4
| TP53   | TUMOR PROTEIN P53
|===


