= Kartlegging omsorgsansvar


== Metadata

Brukes for å registrere kartleggingsspørsmål om et individ har ansvar/omsorg for mindreårige barn og andre individer over 18 år i forbindelse med prosjektet Strukturert Kreftjournal. 

Dette templatet vil bli brukt i prosjektet Strukturert Kreftjournal under sosialanamnese. 

Arketypen Kartleggingsspørsmål om sosiale forhold (openEHR-EHR-OBSERVATION.social_context_screening.v1) er benyttet med to spørsmål, ett for om pasienten har ansvar for barn under 18 år og et spørsmål for om pasienten har ansvar for egne barn/andre over 18 år. 

Småtemplatet med det standardiserte verdisettet kan benyttes utenfor Strukturert kreftjournal hvor det lagres data om kartleggingsspørsmål om omsorgsansvar.

TemplateId:: omsorgsansvar_kartlegging


Archetype:: openEHR-EHR-OBSERVATION.social_context_screening.v1




:toc:




== Kartlegging omsorgsansvar
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging omsorgsansvar* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.social_context_screening.v1_
|at0034| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Kartlegging av om individet har omsorgsansvar (no.onk.sosiale_forhold: OA)


I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for kartleggingsformål. no.onk.sosiale_forhold.
5+a|*Omsorgsperson for barn under 18 år* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Ansvarlig for barn under 18 år (no.onk.sosiale_forhold: U18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Har pasienten ansvar for barn under 18 år?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 
5+a|*Barn som pårørende* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Barn som pårørende (no.onk.sosiale_forhold: BPU18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Finnes det barn som pårørende?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 
|at0025| 0..1| DV_TEXT | Kommentar
a|
5+a|*Omsorgsperson for personer over 18 år* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Ansvarlig for barn/andre over 18 år (no.onk.sosiale_forhold: O18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Har pasienten ansvar for egne barn/andre over 18 år?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 
|====
